import { ReactNode } from "react";
import {
  Stack,
  Container,
  Box,
  Flex,
  Text,
  Heading,
  SimpleGrid,
} from "@chakra-ui/react";
import SmallTitleWithBar from "../../components/SmallTitleWithBar";
import WrapContent from "../../layout/WrapContent";

export default function Details() {
  return (
    <Box bg={"gray.800"} position={"relative"}>
      <WrapContent>
        <Flex
          flex={1}
          zIndex={0}
          display={{ base: "none", lg: "flex" }}
          backgroundImage="url('/images/img2.jpg')"
          backgroundSize={"cover"}
          backgroundPosition="center"
          backgroundRepeat="no-repeat"
          position={"absolute"}
          width={"50%"}
          insetY={0}
          right={0}
        >
          <Flex
            bgGradient={"linear(to-r, gray.800 10%, transparent)"}
            w={"full"}
            h={"full"}
          />
        </Flex>
        <Box maxW={"7xl"} zIndex={10} position={"relative"}>
          <Stack direction={{ base: "column", lg: "row" }}>
            <Stack
              flex={1}
              color={"gray.400"}
              justify={{ lg: "center" }}
              py={{ base: 4, md: 20, xl: 60 }}
            >
              <Box mb={{ base: 8, md: 20 }}>
                {/* <Text
                fontFamily={"heading"}
                fontWeight={700}
                textTransform={"uppercase"}
                mb={3}
                fontSize={"xl"}
                color={"gray.500"}
                >
                Technology
              </Text> */}
                <SmallTitleWithBar title={"OUR HISTORY"} color="gray.500" />
                <Heading
                  color={"white"}
                  mb={5}
                  fontSize={{ base: "3xl", md: "5xl" }}
                >
                  Excellence established in 1984
                </Heading>
                <Text fontSize={"xl"} color={"gray.400"}>
                  Contrary to popular belief, Lorem Ipsum is not simply random
                  text. It has roots in a piece of classical Latin literature
                  from 45 BC, making it over 2000 years old.
                </Text>
              </Box>

              <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
                {stats.map((stat) => (
                  <Box key={stat.title}>
                    <Text
                      fontFamily={"heading"}
                      fontSize={"3xl"}
                      color={"white"}
                      mb={3}
                    >
                      {stat.title}
                    </Text>
                    <Text fontSize={"xl"} color={"gray.400"}>
                      {stat.content}
                    </Text>
                  </Box>
                ))}
              </SimpleGrid>
            </Stack>
            <Flex flex={1} />
          </Stack>
        </Box>
      </WrapContent>
    </Box>
  );
}

const StatsText = ({ children }) => (
  <Text as={"span"} fontWeight={700} color={"white"}>
    {children}
  </Text>
);

const stats = [
  {
    title: "100+",
    content: (
      <>
        <StatsText>projects delivered</StatsText> timely and with perfect
        execution from inception till date
      </>
    ),
  },
  {
    title: "30+",
    content: (
      <>
        <StatsText>states</StatsText> coverage and reach. We have executed
        projects in over 30+ states of the federation.
      </>
    ),
  },
  {
    title: "13%",
    content: (
      <>
        <StatsText>revenues</StatsText> generated by Company™ goes to charity
        and employee safety contribution
      </>
    ),
  },
  {
    title: "$250M+",
    content: (
      <>
        <StatsText>worth</StatsText> of projects executed professionally by
        Company™ as at 2020
      </>
    ),
  },
];
